# -------------------------------------------------------------
# ! DO NOT EDIT !
# Config file automatically generated by <infra-helper>
# Date : <%= date %>
# -------------------------------------------------------------

export JICOFO_PASSWORD=<%= jicofo_password %>
export JVB_PASSWORD=<%= jvb_password %>
export APP_ID=<%= app_id %>
export APP_PASSWORD=<%= app_password %>
