
# -------------------------------------------------------------
# !!!!!!! DO NOT EDIT !!!!!!!!
# Config file automatically generated by <setup-infra>
# Purpose     : Provide Nginx config to a specific server
# Server name : <%= public_domain %>
# Date        : <%= date %>
# -------------------------------------------------------------


proxy_cache_path <%= cache_dir %>/<%= public_domain %> levels=1:2 keys_zone=<%= public_domain %>_keys_zone:10m max_size=10g inactive=60m;
server {
	listen <%= public_http_port %>;
	listen [::]:<%= public_http_port %>;
	server_name <%= public_domain %>; 
	location / {
		return  301 https://$host$request_uri;
	}
}
server {
	listen <%= public_https_port %> ssl;
	listen [::]:<%= public_https_port %> ssl;	
	#
	root <%= server_dir %>;
	server_name <%= public_domain %>; 
	client_max_body_size <%= max_body_size %>;

	# Security headers
	add_header X-Content-Type-Options nosniff;
	add_header X-XSS-Protection "1; mode=block";

	set $prefix "";

	include /etc/drumee/ssl/public.conf;
	include /etc/drumee/infrastructure/internals/accel.public.conf;
	include /etc/drumee/infrastructure/routes/public.conf;
	include /etc/drumee/infrastructure/mfs.public.conf;
}


