
# -------------------------------------------------------------
# !!!!!!! DO NOT EDIT !!!!!!!!
# Config file automatically generated by <infra-helper>
# Purpose     : Provide Nginx config to a specific server
# Server name : <%= domain %>
# Date        : <%= date %>
# -------------------------------------------------------------


proxy_cache_path <%= cache_dir %>/<%= domain %> levels=1:2 keys_zone=<%= domain %>_keys_zone:10m max_size=10g inactive=60m;
server {
	listen 80;
	listen [::]:80;
	server_name <%= domain %>; 
	location / {
		return  301 https://$host$request_uri;
	}
}
server {
	listen 443 ssl;
	listen [::]:443 ssl;	
	#
	root <%= server_dir %>;
	server_name _; 
	client_max_body_size <%= max_body_size %>;
	include /etc/drumee/ssl/main.conf;
	include /etc/drumee/infrastructure/routes/*.conf;
	include /etc/drumee/infrastructure/internals/*.conf;
	include /etc/drumee/infrastructure/mfs.conf;
}


