
# -------------------------------------------------------------
# !!!!!!! DO NOT EDIT !!!!!!!!
# Config file automatically generated by <setup-infra>
# Purpose     : Provide Nginx config to a specific server
# Server name : loopback
# Date        : <%= date %>
# -------------------------------------------------------------


proxy_cache_path <%= cache_dir %>/loopback levels=1:2 keys_zone=loopback_keys_zone:10m max_size=10g inactive=60m;
server {
	listen 127.0.0.1:<%= public_http_port %>;
	server_name _; 
	#
	root <%= server_dir %>;
	server_name _; 
	client_max_body_size <%= max_body_size %>;

	# Security headers
	add_header X-Content-Type-Options nosniff;
	add_header X-XSS-Protection "1; mode=block";

	set $prefix "";

	include /etc/drumee/ssl/main.conf;
	include /etc/drumee/infrastructure/routes/*.conf;
	include /etc/drumee/infrastructure/internals/*.conf;
	include /etc/drumee/infrastructure/mfs.conf;
}


