# -------------------------------------------------------------
# ! DO NOT EDIT !
# Config file automatically generated by <infra-setup>
# Date : <%= date %>
# -------------------------------------------------------------

export ACME_CA_SERVER=<%= ca_server %>
export ACME_CERTS_DIR=<%= certs_dir %>
export ACME_DIR=<%= acme_dir %>
export ACME_EMAIL_ACCOUNT=<%= acme_email_account %>
export ACME_STORE=<%= certs_dir %>/<%= domain_name %>_ecc
export APP_ROUTING_MARK=<%= public_ui_root %>
export CREDENTIAL_DIR=/etc/drumee/credential
export NSUPDATE_KEY=<%= nsupdate_key %>
export NSUPDATE_SERVER=ns1.<%= domain_name %>
export NSUPDATE_ZONE=<%= domain_name %>
export DRUMEE_DB_DIR=<%= db_dir %>
export DRUMEE_CACHE_DIR=<%= cache_dir %>
export DRUMEE_DATA_DIR=<%= data_dir %>
export DRUMEE_DOMAIN_NAME=<%= domain_name %>
export DRUMEE_EXPORT_DIR=<%= export_dir %>
export DRUMEE_IMPORT_DIR=<%= import_dir %>
export DRUMEE_LOG_DIR=<%= log_dir %>
export DRUMEE_MFS_DIR=<%= data_dir %>/mfs
export DRUMEE_ROOT='/srv/drumee'
export DRUMEE_RUNTIME_DIR=<%= runtime_dir %>
export DRUMEE_SCHEMAS_DIR=<%= runtime_dir %>/server/schemas
export DRUMEE_SERVER_HOME=<%= server_dir %>
export DRUMEE_SERVER_NODE=<%= runtime_dir %>/dist/main/node_modules
export DRUMEE_STATIC_DIR=<%= static_dir %>
export DRUMEE_SYSTEM_GROUP=<%= system_group %>
export DRUMEE_SYSTEM_USER=<%= system_user %>
export DRUMEE_TMP_DIR=<%= runtime_dir %>/tmp
export DRUMEE_UI_HOME=<%= runtime_dir %>/ui
export DRUMEE_BACKUP_LOCATION=<%= BACKUP_LOCATION %>
export DRUMEE_DB_BACKUP=<%= db_backup %>
export JITSI_DOMAIN=<%= jitsi_domain %>
export OWN_CERTS_DIR=<%= own_certs_dir %>
export PUBLIC_UI_ROOT=<%= public_ui_root %>

if [ -d "$OWN_CERTS_DIR" ]; then
  export ACME_DIR="$OWN_CERTS_DIR"
fi
