/* -------------------------------------------------------------
# !!!!!!! DO NOT EDIT !!!!!!!!
# Config file automatically generated by <infra-helper>
# Purpose  : Provide route (instance) to Nginx
# Date     : <%= date %>
# ------------------------------------------------------------- */

module.exports = require("<%= ecosystem %>");
