# -------------------------------------------------------------
# ! DO NOT EDIT !
# Config file automatically generated by <setup-infra>
# Date : <%= date %>
# -------------------------------------------------------------

ssl_certificate_key <%= certs_dir %>/<%= domain %>_ecc/<%= domain %>.key;
ssl_certificate <%= certs_dir %>/<%= domain %>_ecc/fullchain.cer;
ssl_trusted_certificate <%= certs_dir %>/<%= domain %>_ecc/ca.cer;

